apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  name: postgres-exporter
spec:
  type: NodePort
  ports:
  - port: 9187
    targetPort: 9187
  selector:
    app: postgres-exporter
