apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mattermost
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: mattermost-deployment
  targetCPUUtilizationPercentage: 80
