apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  labels:
    app: postgres
type: Opaque
data:
  pg-username: bWF0dGVybW9zdA==
  pg-password: bWF0dGVybW9zdA==
  init-monitoring.sql: Q1JFQVRFIFVTRVIgbW9uaXRvcmluZyBQQVNTV09SRCAncHJvbWV0aGV1cyc7DQpBTFRFUiBVU0VSIG1vbml0b3JpbmcgU0VUIFNFQVJDSF9QQVRIIFRPIG1vbml0b3JpbmcscGdfY2F0YWxvZzsNCg0KQ1JFQVRFIFNDSEVNQSBtb25pdG9yaW5nIEFVVEhPUklaQVRJT04gbW9uaXRvcmluZzsNCg0KQ1JFQVRFIFZJRVcgbW9uaXRvcmluZy5wZ19zdGF0X2FjdGl2aXR5DQpBUw0KICBTRUxFQ1QgKiBmcm9tIHBnX2NhdGFsb2cucGdfc3RhdF9hY3Rpdml0eTsNCg0KR1JBTlQgU0VMRUNUIE9OIG1vbml0b3JpbmcucGdfc3RhdF9hY3Rpdml0eSBUTyBtb25pdG9yaW5nOw0KDQpDUkVBVEUgVklFVyBtb25pdG9yaW5nLnBnX3N0YXRfcmVwbGljYXRpb24gQVMNCiAgU0VMRUNUICogZnJvbSBwZ19jYXRhbG9nLnBnX3N0YXRfcmVwbGljYXRpb247DQoNCkdSQU5UIFNFTEVDVCBPTiBtb25pdG9yaW5nLnBnX3N0YXRfcmVwbGljYXRpb24gVE8gbW9uaXRvcmluZzsNCg==
